Lesson 1
trubinart/django-based pull request #1
Opened 2021-01-19 15:39 UTC by trubinart

все сделал

2021-01-19 16:13 UTC, Vokler requested changes
Вы инициализировали гит не в той папке. То есть у вас еще в репозиторий улетел env. Просмотрите урок в конце внимательнее.

2021-01-19 16:13 UTC, Vokler commented on geekshop/.gitignore
> +
Лучше вручную создать файл .gitignore. Когда автоматически - куча всего того, что нет в проекте. К тому же у вас в репозитории все равно остались db.sqlite3, .idea

2021-01-19 16:13 UTC, Vokler commented on geekshop/geekshop/settings.py
> +    os.path.join(BASE_DIR, "static"),
Используйте везде одинаковый стиль кавычек

2021-01-20 06:00 UTC, trubinart commented on geekshop/.gitignore
> +
@Vokler все исправил, только не знаю как удалит файлы из env из pull request
но, вы можете посмотреть чистую ветку Lesson_1
https://github.com/trubinart/django-based/tree/lesson_1

2021-01-20 06:01 UTC, trubinart commented on geekshop/.gitignore
> +
кстати, не подскажете, как удалить удаленные файлы из пулла?

2021-01-20 11:38 UTC, Vokler commented on geekshop/.gitignore
> +
Вы имеете в виду, как удалить файла, которые уже в репозитории?

2021-01-20 11:39 UTC, Vokler commented on geekshop/.gitignore
> +
Сейчас более-менее все ок, но у вас почему в папке geekshop (которая должна быть корневой и содержать в себе только `settings.py`, `urls.py`, `__ini__.py` и `wsgi.py`) находятся все папки проекта. Посмотрите пример, который приложен к уроку. Структура должна быть такая же

2021-01-20 12:14 UTC, trubinart commented on geekshop/.gitignore
> +
@Vokler да, что делать, если:
1. Я залил файлы в репо
2. Сделал пулл реквест
3. Удалил из файлы из репо
4. Файлы в пулл реквест остались, но они помечены удаленными - как их полностью удалить из списка?

2021-01-20 12:19 UTC, trubinart commented on geekshop/.gitignore
> +
@Vokler Файлы проекта тоже откорректировал
https://github.com/trubinart/django-based/tree/lesson_1

2021-01-20 12:59 UTC, Vokler commented on geekshop/.gitignore
> +
Они наверное помечаются удаленными, но когда мы смержим ветку в master, их уже не будет

Сейчас по структуре проекта и по коду замечаний нет!

2021-01-20 12:59 UTC, merged